apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adhub-frontend
  labels:
    app: adhub
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: adhub
        tier: frontend
    spec:
      containers:
      - name: adhub-app
        image: gcr.io/[GCLOUD_PROJECT]/adhub
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
