apiVersion: v1
kind: Service
metadata:
  name: adhub-frontend
  labels:
    app: adhub
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: adhub
    tier: frontend
