apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adhub-worker
  labels:
    app: adhub
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: adhub
        tier: worker
    spec:
      containers:
      - name: adhub-app
        image: gcr.io/superb-heaven-155622/adhub
        imagePullPolicy: Always
        env:
        - name: SCRIPT
          value: worker.js
